-- MySQL Script generated by MySQL Workbench
-- Wed Feb  6 21:09:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema cloud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS cloud DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema
-- -----------------------------------------------------
USE cloud ;

-- -----------------------------------------------------
-- Table cloud.concursos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cloud.concursos (
  idconcursos INT NOT NULL,
  fecha_inicio DATETIME NULL,
  fecha_fin DATETIME NULL,
  valor DECIMAL(2),
  guion VARCHAR(150) NULL,
  recomendaciones VARCHAR(150) NULL,
  url VARCHAR(100) NOT NULL,
  banner BLOB NULL,
  nombre VARCHAR(95) NULL,
  PRIMARY KEY (idconcursos))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table cloud.cuenta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cloud.cuenta (
  idcuenta INT NOT NULL,
  nombre VARCHAR(90) NOT NULL,
  segundo_nombre VARCHAR(90) NULL,
  apellido VARCHAR(90) NOT NULL,
  correo VARCHAR(90) unique,
  contrasena VARCHAR(45)NOT NULL,
  segundo_apellido VARCHAR(90) NULL,
  PRIMARY KEY (idcuenta))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table cloud.gestion_concurso
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cloud.gestion_concurso (
  idgestion_concurso INT NOT NULL,
  concursos INT NULL,
  creador INT NULL,
  PRIMARY KEY (idgestion_concurso),
  CONSTRAINT concursos
    FOREIGN KEY (concursos)
    REFERENCES cloud.concursos (idconcursos)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT creador
    FOREIGN KEY (creador)
    REFERENCES cloud.cuenta (idcuenta)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table cloud.usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cloud.usuario (
  idusuario INT NOT NULL,
  nombre VARCHAR(90) NOT NULL,
  segundo_nombre VARCHAR(90) NULL,
  apellido VARCHAR(90) NOT NULL,
  segundo_apellido VARCHAR(90) NULL,
  correo VARCHAR(45) unique NOT NULL,
  PRIMARY KEY (idusuario))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table cloud.estado
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cloud.estado (
  idestado INT NOT NULL,
  nombre VARCHAR(45) NULL,
  descripcion VARCHAR(45) NULL,
  PRIMARY KEY (idestado))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table cloud.archivos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cloud.archivos (
  idarchivos INT NOT NULL,
  observaciones VARCHAR(150) NULL,
  usuario INT NULL,
  estado INT NULL,
  voz_inicial BLOB NULL,
  concurso INT NULL,
  fecha DATETIME NULL,
  voz_mp3 BLOB NULL,
  extension VARCHAR(45) NULL,
  PRIMARY KEY (idarchivos),
  CONSTRAINT usuario
    FOREIGN KEY (usuario)
    REFERENCES cloud.usuario (idusuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT estado
    FOREIGN KEY (estado)
    REFERENCES cloud.estado (idestado)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT concurso
    FOREIGN KEY (concurso)
    REFERENCES cloud.concursos (idconcursos)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
